symbolicLinks:
- destination: "%LOCALAPPDATA%\\nvim"
  source: "$PSScriptRoot\\nvim"
- destination: "%USERPROFILE%\\jmelosegui-omp.json"
  source: "$PSScriptRoot\\oh-my-posh\\jmelosegui-omp.json"
- destination: "%USERPROFILE%\\AppData\\Roaming\\Code\\User\\settings.json"
  source: "$PSScriptRoot\\vscode\\settings.json"
- destination: "%USERPROFILE%\\AppData\\Roaming\\Code\\User\\keybindings.json"
  source: "$PSScriptRoot\\vscode\\keybindings.json"
- destination: "%USERPROFILE%\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1"
  source: "$PSScriptRoot\\powershell\\profile.ps1"
- destination: "%USERPROFILE%\\Documents\\PowerShell\\Microsoft.VSCode_profile.ps1"
  source: "$PSScriptRoot\\powershell\\profile.ps1"
- destination: "%USERPROFILE%\\Documents\\PowerShell\\Microsoft.PowerShell_profile.ps1"
  source: "$PSScriptRoot\\powershell\\profile.ps1"
