symbolicLinks:
- destination: "%LOCALAPPDATA%\\nvim"
  source: "$PSScriptRoot\\apps\\nvim"
- destination: "%USERPROFILE%\\jmelosegui-omp.json"
  source: "$PSScriptRoot\\apps\\oh-my-posh\\jmelosegui-omp.json"
- destination: "%USERPROFILE%\\AppData\\Roaming\\Code\\User\\settings.json"
  source: "$PSScriptRoot\\apps\\vscode\\settings.json"
- destination: "%USERPROFILE%\\AppData\\Roaming\\Code\\User\\keybindings.json"
  source: "$PSScriptRoot\\apps\\vscode\\keybindings.json"
- destination: "%USERPROFILE%\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1"
  source: "$PSScriptRoot\\aaps\\powershell\\profile.ps1"
- destination: "%USERPROFILE%\\Documents\\PowerShell\\Microsoft.VSCode_profile.ps1"
  source: "$PSScriptRoot\\apps\\powershell\\profile.ps1"
- destination: "%USERPROFILE%\\Documents\\PowerShell\\Microsoft.PowerShell_profile.ps1"
  source: "$PSScriptRoot\\apps\\powershell\\profile.ps1"
- destination: "%USERPROFILE%\\.config\\fastfetch\\config.jsonc"
  source: "$PSScriptRoot\\apps\\fastfetch\\config.jsonc"
- destination: "%LOCALAPPDATA%\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json"
  source: "$PSScriptRoot\\apps\\windows-terminal\\settings.json"

