# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2.0
# WinGet DSC Configuration File

properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Neovim
      directives:
        description: Installing Neovim
        allowPrerelease: true
      settings:
        id: Neovim.Neovim
        source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Rider
      directives:
        description: Installing JetBrains Rider
        allowPrerelease: true
      settings:
        id: JetBrains.Rider
        source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VSCode
      directives:
        description: Installing Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: OhMyPosh
      directives:
        description: Installing Oh My Posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Fastfetch
      directives:
        description: Installing Fastfetch
        allowPrerelease: true
      settings:
        id: Fastfetch-cli.Fastfetch
        source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ripgrep
      directives:
        description: Installing ripgrep
        allowPrerelease: true
      settings:
        id: BurntSushi.ripgrep.MSVC
        source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Ubuntu-22.04
      directives:
        description: Installing Ubuntu 22.04
        allowPrerelease: true
      settings:
        id: Canonical.Ubuntu.2204
        source: winget
        Ensure: Present